language: python
python:
  - '3.7'
install:
  - pip install .
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov-report term --cov=RME RME/tests/
after_success:
  - codecov
