language: python
python:
  - '3.7'
install:
  - pip install .
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --pyargs RME/RME --cov=RME
after_success:
  - codecov
